var menu = d3.select("body")
  .insert("div", ":first-child")
  .attr("class", "menu")
  .append("div")

menu.append("p").append("a").attr("href", "http://creativecommons.org/licenses/by-sa/4.0/")
  .attr("target", "_blank")
  .attr("rel", "license")
  .append("img").attr("src", "../utils/cc-by-sa.png")

var ul = menu.append("ul")
ul.append("li")
  .append("a").attr("href", "siem-marie")
  .text("logees van Siem en Marie")

menu.append("p").append("a").attr("href", "https://familiepol.wordpress.com/contact/")
  .attr("target", "_blank")
  .text("contact")
menu.append("p").append("a").attr("href", "https://github.com/pol-ulderink/pol-ulderink.github.io/commits/master")
  .attr("target", "_blank")
  .text("laatste wijzigingen")

var p = menu.append("p")
p.append("a").attr("href", "https://help.github.com/articles/editing-files-in-another-user-s-repository/")
  .attr("target", "_blank")
  .text("Wijzigingsvoorstel indienen")
p.append("span").text(" op een van de ")
p.append("a").attr("href", "https://github.com/pol-ulderink/pol-ulderink.github.io/find/master")
  .attr("target", "_blank")
  .text("pagina's")

var b = d3.select("body").insert("div", ":first-child").attr("id","banner")
b.append("h1")
  .append("a").attr("href", "../")
  .text("Pol-Ulderink")
b.append("p")
  .text("Verhalen en illustraties bij een stamboom")
