var menu = d3.select("body")
  .insert("div", ":first-child")
  .attr("class", "menu")
  .append("div")

menu.append("p").append("a")
  .attr("href", "http://creativecommons.org/licenses/by-sa/4.0/")
  .attr("target", "_blank")
  .attr("rel", "license")
  .append("img").attr("src", "../utils/cc-by-sa.png")

var ul = menu.append("ul")
var li = ul.append("li")
li.append("a")
  .attr("href", "siem-marie")
  .text("logees van Siem en Marie")
li.append("span").text(" ")
li.append("a")
  .attr("rel", "history")
  .attr("target", "_blank")
  .attr("title", "geschiedenis\nvan de pagina")
  .attr("href", "https://github.com/pol-ulderink/pol-ulderink.github.io/commits/master/siem-marie")
  .node().innerHTML = "&#x25A4;" // SQUARE WITH HORIZONTAL FILL
li.append("a")
  .attr("rel", "source")
  .attr("target", "_blank")
  .attr("title", "wijzigingen voorstellen:\nvolg het potlood\ninloggen\nnog een potlood volgen\ninstructies en groene knoppen volgen")
  .attr("href", "https://github.com/pol-ulderink/pol-ulderink.github.io/blob/master/siem-marie/index.html")
  .node().innerHTML = "&#x270E;" // pencil

menu.append("p").append("a")
  .attr("href", "https://familiepol.wordpress.com/contact/")
  .attr("target", "_blank")
  .text("contact")

var b = d3.select("body").insert("div", ":first-child").attr("id","banner")
b.append("h1")
  .append("a").attr("href", "../")
  .text("Pol-Ulderink")
b.append("p")
  .text("Verhalen en illustraties bij een stamboom")
